<?php

function top_author_votingapi_insert($votes) {
  //dpm($votes);
//getting uid of recently voted node
  $id = $votes[0]['entity_id'];
  //dpm($id);
  $query = db_select('node', 'n');
  $query->innerjoin('votingapi_vote', 'v', 'n.nid = v.entity_id');
  $query->fields('n', array('uid'))
  ->condition('v.entity_id', $id, '=');
  $cuid = $query->execute();
 // dpm($cuid);
  $currentuid = $cuid->fetchAssoc();
  dpm('uid of currently voted node ' . $currentuid['uid']);
//getting upvotes of uid whose node is currently voted
  $query = db_select('node', 'n');
  $query->innerjoin('votingapi_vote', 'v', 'n.nid = v.entity_id');
  $query->fields('n', array('uid'))
  //->fields('v',array('value', 'entity_id'))
  ->condition('v.value', '1', '=')
  ->condition('v.entity_type', 'node', '=')
  ->condition('n.uid', $currentuid, '=');
  $query->addExpression("COUNT(n.nid)", 'count');
  $currentupvotes = $query->execute();
  $cup = $currentupvotes->fetchAssoc();
  dpm('total upvotes of current voted user ' . $cup['count']);
  /* Calculating top 5 authors */
  $query = db_select('node', 'n');
  $query->innerjoin('votingapi_vote', 'v', 'n.nid = v.entity_id');
  $query->fields('n', array('uid'))
  ->fields('v', array('value', 'entity_type'))
  ->condition('v.value', '1', '=')
  ->condition('v.entity_type', 'node', '=')
  ->condition('n.uid', $currentuid, '!=')
  ->groupBy('n.uid')
  ->orderBy($query->addExpression("COUNT(n.nid)", 'count'), 'DESC')
  ->range(0, 3);
  $result = $query->execute();
  $res = array();
  $i = 0;
  while ($record = $result->fetchAssoc()) {
    dpm($record['uid'] . ' ' . $record['count']);
    $res[$i++] = $record['count'];
    $u = $record['uid'];
  }
  $min = min($res);
  dpm('min of top authors ' . $min);

  if ($cup['count'] > $min) {
  dpm('entering uid = ' . $cup['uid']);
  dpm('remove uid = ' . $u);
  $author = user_load($u);
  dpm($author);
  $params = array(
    'subject' => "Removed From Top 5 Author's List.",
    'body' => "Sorry to inform you that you are no longer in top five Author's List at IdeaZone.",
    );
    drupal_mail('top_author', 'top_author_mail', $author->mail, language_default(), $params);
    drupal_set_message(("Sent regret mail to " . $author->mail));

    $author = user_load($cup['uid']);
    dpm($author);
    $params = array(
      'subject' => "Entry in Top 5 Author's List.",
      'body' => "Congratulations! You are now in top five Author's List at IdeaZone.",
      'username' => $author->name,
      );
    drupal_mail('top_author', 'top_author_mail', $author->mail, language_default(), $params);
    drupal_set_message(t("Sent contratulations mail to " . $author->mail));
  }

  }
/**
 * Implementation of hook_mail().
 */
function top_author_mail($key, &$message, $params) {
  switch ($key) {
    case 'top_author_mail':
      $message['subject'] = $params['subject'];
      $message['body'][] = t('Hello @username,', array('@username' => $params['username']));
      $message['body'][] = $params['body'];
      break;
  }
}