<?php
/**
 * Implements hook_action_info().
 */
function custom_action_vbo_action_info() {
  return array(
    'myidea_approve' => array( // declare the function name to be used.
    'type' => 'node', // can be node,comment etc
    'label' => t('Approve Idea'), // the name of the operation which is displayed to the user.
    'configurable' => FALSE,
    'pass rows' => TRUE,//entire views row is passed as context in action callback.
    ),
    'myidea_reject' => array( // declare the function name to be used.
    'type' => 'node', // can be node,comment etc
    'label' => t('Reject Idea'), // the name of the operation which is displayed to the user.
    'configurable' => FALSE,
    'pass rows' => TRUE,//entire views row is passed as context in action callback.
    ),
    );
}
/**
 * Implements callback function to approve idea
 */
function myidea_approve($entity, $context) {
  //dpm($context);
  //dpm($entity);
  //$account = user_load_by_name($context['author']);
  $node = node_load($entity->nid);
  $node->field_status['und'][0]['value'] = 4;
  node_save($node);
  /* Creating custom node of type myplans*/
  $nwnode = new stdClass(); // We create a new node object
  $nwnode->type = 'myplans'; // Or any other content type you want
  $nwnode->title = $node->title;
  $nwnode->language = 'und';
  node_object_prepare($nwnode); // Set some default values.
  $nwnode->uid = $node->uid; // Or any id you wish
  // Let's add standard body field
  $nwnode->body[$node->language][0]['value'] = $node->body['und'][0]['value'];
  //$nwnode->body[$node->language][0]['summary'] = 'Here goes a summary';
  $nwnode->body['und'][0]['format'] = $node->body['und'][0]['format'];
  $nwnode->field_plan_status[$node->language][0]['value'] = 'new';
  $nwnode->field_plan_tags = $node->field_free_tags;
  $nwnode = node_submit($nwnode); // Prepare node for a submit
  node_save($nwnode); // After this call we'll get a nid
}
/**
 * Implements callback function to reject idea
 */
function myidea_reject($entity, $context) {
  //dpm($context);
  //dpm($entity);
  //$account = user_load_by_name($context['author']);
  $node = node_load($entity->nid);
  $node->field_status['und'][0]['value'] = 5;
  node_save($node);
}